0install/0install

ocaml/tests/solves.xml
I've redesigned the solver unit tests in the C# version of Zero Install to use an XML test case file like the OCaml version does to enable sharing of test cases. This patch simply adds all ported test cases from the C# version.
Some may be redundant/duplicates of existing tests and I haven't tested them in the OCaml build yet (waiting for Travis CI to do that for me).
=> Add test cases ported from C# version

ocaml/myocamlbuild.ml
Before ocamlbuild 0.11, ocamlbuild would build gui_gtk.cmxs from
gui_gtk.cmx directly, and (succesfully) use the "link_gtk" tag at this
step, generating a command-line of the form (details elided):
ocamlfind ocamlopt -shared -package ...
lablgtk.cmxa lwt-glib.cmxa
gui_gtk.cmx
-o gui_gtk.cmxs
which works just fine.
With ocamlbuild 0.11, the ocamlbuild rules regarding cmx, cmxa and
cmxs have been changed, and the build path is now
`gui_gtk.cmx -> gui_gtk.cmxa -> gui_gtk.cmxs`. On the first step,
producing gui_gtk.cmxa would fail, as link_gtk would also apply
and produce a command-line of the form
ocamlfind ocamlopt -a -package ...
lablgtk.cmxa lwt-glib.cmxa
gui_gtk.cmx
-o gui_gtk.cmxa
This fails with the following error:
Option -a cannot be used with .cmxa input files.
Command exited with …
=> ocaml/myocamlbuild.ml: restrict link_gtk to shared linking

README.md, ocaml/.merlin, ocaml/_tags, ocaml/support.mlpack, ocaml/support/base64.ml, ocaml/support/base64.mli, opam
We were only using the Base64 module (we now bundle a simple decoder).
Note: testing with afl-fuzz, it seems that the new decoder is stricter than extlib about malformed input, but it should process valid input the same.
=> Remove dependency on extlib

ocaml/_tags, ocaml/support/gpg.ml, ocaml/tests/fake_gpg_agent.ml, ocaml/zeroinstall/json_connection.ml
We now depend on a recent Lwt anyway.
This reverts commit 5b32a90ed160c3523a46addd747a9c45a49f56ec.
=> Re-enable safe-string everywhere

README.md, ocaml/Makefile, ocaml/myocamlbuild.ml, ocaml/support/_tags, ocaml/support/hash.cppo.ml, ocaml/support/windows_api.cppo.ml, ocaml/zeroinstall/_tags, ocaml/zeroinstall/dbus.cppo.ml, opam
camlp4 is old, large and incompatible with newer technologies such as ppx and jbuilder.
=> Replace camlp4 build dependency with cppo

ocaml/zeroinstall/gui.ml
This will (eventually) allow us to move the web-site to a server that doesn't support php.
=> Use api.0install.net for bug reports

ocaml/_tags, ocaml/gui_gtk/_tags, ocaml/myocamlbuild.ml
=> Fix build for Lwt 3.0

ocaml/gui_gtk/solver_box.ml, ocaml/options.mli, ocaml/support/gpg.ml, ocaml/tests/fake_distro.ml, ocaml/tests/test_distro.ml, ocaml/tests/test_driver.ml, ocaml/tests/test_packagekit.ml, ocaml/tests/test_solver.ml, ocaml/zeroinstall/apps.mli, ocaml/zeroinstall/compiled.ml, ocaml/zeroinstall/distro.ml, ocaml/zeroinstall/distro.mli, ocaml/zeroinstall/distro_impls.ml, ocaml/zeroinstall/distro_impls.mli, ocaml/zeroinstall/driver.ml, ocaml/zeroinstall/driver.mli, ocaml/zeroinstall/feed.ml, ocaml/zeroinstall/feed_provider_impl.ml, ocaml/zeroinstall/fetch.ml, ocaml/zeroinstall/fetch.mli, ocaml/zeroinstall/gui.mli, ocaml/zeroinstall/host_python.ml, ocaml/zeroinstall/impl.ml, ocaml/zeroinstall/impl.mli, ocaml/zeroinstall/impl_provider.ml, ocaml/zeroinstall/packagekit.ml, ocaml/zeroinstall/solver.ml, ocaml/zeroinstall/ui.mli
- Separate out `Distro.t` from the provider API. This makes it clearer which parts of the API are for users of distributions, and which are things that should be provided by each distribution implementation.
- Split out the interface that *must* be implemented (`Distro.provider`) from the helper base-class (`distribution`).
- Move `Distro.query` to a submodule, make it abstract, and add some helper functions.
- Remove unused `?init` argument on `get_impls_for_feed`.
- Use OCaml 4.02 match exception syntax.
- Fix package filtering on Debian. We intended to pass only available packages to PackageKit, but treated a cached negative result as a valid package.
- Add progress for apt-cache queries, so they are visible and can be cancelled.
=> Tidy distribution code

ocaml/zeroinstall/downloader.ml, ocaml/zeroinstall/fetch.ml
When this happens sf.net returns a success code, but the content is just a textual error saying "SourceForge is currently in Disaster Recovery mode".
We now treat this as a network failure and try the mirror instead.
/cc @bastianeicher
=> Detect when SourceForge is in Disaster Recovery mode

.travis-extra-deps.sh
Error was:
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-2
Target /usr/local/bin/2to3-2
is a symlink belonging to python. You can unlink it:
brew unlink python
=> Fix Travis tests on macOS

.travis.yml, ocaml/tests/fake_system.ml, ocaml/zeroinstall/host_python.ml
On Debian (Python 3.5.3), `__path__` is a string, but on macOS (Python 3.6.5) it's a list.
Error was:
warning: Failed to get details from Python: Bad JSON: ...
=> Fix host Python test on macOS

ocaml/zeroinstall/command.ml, ocaml/zeroinstall/command.mli, ocaml/zeroinstall/exec.ml, ocaml/zeroinstall/selections.ml, ocaml/zeroinstall/selections.mli
Replace the previous work-around for the OCaml 4.07 with some tidier code that doesn't need it.
=> Clean up command-building code

ocaml/man.ml, ocaml/support.mlpack, ocaml/support/common.ml, ocaml/support/env.ml, ocaml/support/env.mli, ocaml/zeroinstall.mlpack, ocaml/zeroinstall/binding.ml, ocaml/zeroinstall/command.mli
Allows removing varname from Common.
Also, tidied the code slightly.
=> Move Env to Support.Env

README.md
The main opam repository has updated to a new format, so opam 1 no longer works.
=> Update README for opam 2

zeroinstall/injector/_runenv.py, zeroinstall/injector/run.py
Recent versions of Python silently fail to pass on environment variables starting with `0` or containing dashes.
=> Rename runenv variables due to Python breakage (for old Python branch)

ocaml/support/dune, ocaml/support/json.ml, ocaml/tests/server.ml, ocaml/zeroinstall/downloader.ml, ocaml/zeroinstall/exec.ml, ocaml/zeroinstall/json_connection.ml, ocaml/zeroinstall/json_connection.mli, ocaml/zeroinstall/requirements.mli
This should be case insensitive. Error was:
info: Download failed: Downloaded archive has incorrect size.
URL: https://downloads.sourceforge.net/project/zero-install/0template/0.6/0template-0.6.tar.bz2
Expected: 17585 bytes
Received: 371 bytes
This might have been caused by using HTTP/2.
Reported by Nick Sabalausky. Fixes https://github.com/0install/0template/issues/14.
Also, suppress some Yojson deprecation warnings.
=> Fix check for HTTP Location header

.travis.yml
Maybe this will fix the gnutls errors, e.g.
Error downloading 'https://downloads.sourceforge.net/project/zero-install/0install/2.14/0install-linux-x86_64-2.14.tar.bz2': gnutls_handshake() failed: Handshake failed
=> Update Travis to use Ubuntu/Xenial

ocaml/zeroinstall/apps.ml
Just log a warning. Otherwise, you can't run an application at all if e.g. the filesystem is read-only, or we are running inside a sandbox (e.g. when an opam build recursively calls the opam binary).
=> Don't abort if we can't save new app selections

ocaml/tests/fake_system.ml
Error was:
Error (alert deprecated): module Stdlib.Pervasives
=> Fix compiler warnings on OCaml 4.08

ZeroInstall.xml, zeroinstall/0launch-gui/gui.py, zeroinstall/__init__.py, zeroinstall/injector/gpg.py
- We can't use Python 3.7 as `async` is now a keyword.
- GnuPG's output format has changed (extra column).
=> More fixes for the old Python version

ocaml/tests/test_0install.ml, ocaml/zeroinstall/config.ml
Google just announced that they will start requiring a credit card for AppEngine apps, so migrate to new host.
=> Use new keylookup.0install.net address for key lookups

0install.opam, ocaml/cli/dune, ocaml/dune, ocaml/gui_gtk/dune, ocaml/tests/dune, ocaml/zeroinstall/dune
Allows setting `(implicit_transitive_deps false)` in `dune-project`, which will be the default for Dune 2. However, that requires dune >= 1.7, and Debian only has 1.6, so don't turn that on yet.
=> Make transitive OCaml library dependencies explicit

.travis-extra-deps.sh, ocaml/cli/common_options.ml, ocaml/tests/test_packagekit.ml, ocaml/zeroinstall/dbus.with.ml, ocaml/zeroinstall/dbus.without.ml, ocaml/zeroinstall/dune, ocaml/zeroinstall/packagekit_stubs.ml
We looked for `obus.network-manager`, but that got renamed to `obus.network_manager` when obus converted to dune.
Also, show whether we were compiled with D-BUS support in the `--version` output.
=> Fix detection of obus library

README.md, ocaml/tests/server.ml, ocaml/tests/test_download.ml, ocaml/zeroinstall/dune, ocaml/zeroinstall/http.cohttp.ml
This adds cohttp as an alternative to using libcurl for downloads. As cohttp doesn't support FTP, this PR also adds a very minimal (and largely untested) FTP client implementation for the few remaining 0install FTP sites.
The advantage is that the resulting binary has many fewer dependencies.
Before:
```
/lib64/ld-linux-x86-64.so.2 (0x00007229eb1f2000)
libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007229ea170000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007229ea764000)
libcurl-gnutls.so.4 => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007229eaaad000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007229ea925000)
libev.so.4 => /usr/lib/x86_64-linux-gnu/libev.so.4 (0x00007229eab5c000)
libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 …
```
=> Add cohttp backend

ocaml/support/utils.ml
We don't want to show stacktraces for expected errors unless `-v` is used.
We previously did this by only enabling stacktraces when `-v` was given. However, newer versions of OCaml enable stacktraces by default.
=> Only show stacktraces with -v

.dockerignore, .travis-extra-deps.sh, .travis.yml, Makefile, ocaml/zeroinstall/http.cohttp.ml, static/.gitignore, static/Dockerfile, static/Dockerfile-test-debian-10, static/Dockerfile-test-fedora-30, static/README.md, static/run-tests.sh
To build portable static binaries, run `make static/dist.tgz` in the top-level directory. This uses Docker. Run `static-test` to test the results. It tests on Debian 10 and Fedora 30 at the moment.
=> Build and test static binaries

ocaml/cli/search.ml, ocaml/tests/fake_gpg_agent.ml, ocaml/tests/fake_gpg_agent.mli, ocaml/tests/test_0install.ml, ocaml/tests/test_feed_cache.ml, ocaml/tests/test_gpg.ml
This is now an error with Lwt 5.0.0.
`0install search` would fail with the error:
Failure("Nested calls to Lwt_main.run are not allowed")
Some of the unit tests also needed to be fixed.
=> Fix use of nested Lwt_main.run

ocaml/zeroinstall/host_python.ml
`http://repo.roscidus.com/python/python` is now `https://apps.0install.net/python/python.xml`, etc.
=> Update fallback host-Python check for new URIs

ocaml/tests/data/solves.xml, ocaml/zeroinstall/diagnostics.ml
The diagnostics system didn't consider dependencies of <command>
elements, resulting in problem reports such as:
- python.xml -> (problem)
Rejected candidates:
3 (3): Reason for rejection unknown: 3-<implementation> at ...=false
&& <command> at ...=true => 0-<implementation>=true
=> Fix bad solver error

ZeroInstall.xml
Copied from https://github.com/0install/0install-feeds/pull/5 - @bastianeicher I assume we should add this here too?
=> Explicitly depend on pywin32 on Windows

.travis-extra-deps.sh
Error was:
==> Pouring python-3.7.6.high_sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink Frameworks/Python.framework/Headers
Target /usr/local/Frameworks/Python.framework/Headers
is a symlink belonging to python@2. You can unlink it:
brew unlink python@2
And also:
pygobject was deleted from homebrew/core in commit fcfa254:
pygobject: delete
Does not support Python 3, and needs pygtk which has been removed.
The 0compile branch has now been updated to work with Python 3 and to avoid pygobject. This PR just removes the instruction to install pygobject.
=> Fix homebrew error

ocaml/cli/update.ml, ocaml/gui_gtk/component_box.ml, ocaml/gui_gtk/component_tree.ml, ocaml/gui_gtk/solver_box.ml, ocaml/solver/diagnostics.ml, ocaml/solver/s.ml, ocaml/solver/solver_core.ml, ocaml/solver/zeroinstall_solver.mli, ocaml/tests/test_sat.ml, ocaml/tests/test_solver.ml, ocaml/zeroinstall/driver.mli, ocaml/zeroinstall/exec.ml, ocaml/zeroinstall/gui.ml, ocaml/zeroinstall/gui.mli, ocaml/zeroinstall/progress.mli, ocaml/zeroinstall/selections.ml, ocaml/zeroinstall/selections.mli, ocaml/zeroinstall/solver.ml, ocaml/zeroinstall/solver.mli, ocaml/zeroinstall/tree.ml
The old API was a bit confusing. The user of the solver had to wrap the solver's return to provide a `SOLVER_RESULT` for the diagnostics.
Now, the user-required bits are in `SOLVER_INPUT` and the solver itself provides the rest.
=> Make the solver return a SOLVER_RESULT

0install.opam
This is more explicit than just asking users to install it where it makes sense, and also means that the CI will test it.
=> Mark obus as required (except on Windows and macOS)

zeroinstall/zerostore/unpack.py
In Python's glob function `*` does not match elements starting with `.`.
This PR adds an additional match against `.*` to align the behavior of the Python version of 0install with the OCaml version.
=> Align .dmg extraction behavior with OCaml version of 0install

.travis-extra-deps.sh, .travis.yml
Also, remove some compiler versions (ocaml-ci checks them faster) and some old stuff we don't need any longer.
Use OCaml 4.09 to avoid having to downgrade the compiler on macOS.
=> Test 0install-gtk with Travis

.dockerignore, static/Dockerfile
Also, exclude `.git` from the build context to save time.
=> Use Debian for static builds to get ARM support

0install-gtk.opam
Otherwise, we might select one of the old beta releases, which doesn't work.
=> Require lablgtk3 >= 3

.github/workflows/mac.yml, .travis.yml, 0install-solver.opam, 0install.opam, appveyor.yml, src/solver/diagnostics.ml, src/solver/dune, src/solver/s.ml, src/solver/solver_core.ml, src/solver/tests/dune, src/solver/tests/test.ml, src/solver/zeroinstall_solver.mli, src/tests/dune, src/tests/test_solver.ml, src/zeroinstall/dune, src/zeroinstall/solver.ml
This PR aims to make 0install's solver usable by other package managers:
- Move the solver to its own opam package (`0install-solver`).
- Add support for "conflict classes". opam uses this to make every compiler conflict with every other compiler, even when they have different names.
- Clean up the Diagnostics code and extend the public API. The default format is designed for 0install and assumes long package names and hashes. This also gives some flexibility in controlling how verbose the output should be.
As an example, https://github.com/talex5/opam-0install-solver uses this to speed up opam.
=> Allow solver to be used outside of 0install

0install-gtk.opam, 0install.opam, src/test_gtk/dune, src/tests/dune, src/tests/fake_system.ml
The old `oUnit` is just a transition package that depends on `ounit2` now.
=> Depend on ounit2 for unit-tests

src/solver/diagnostics.ml, src/solver/s.ml, src/solver/tests/test.ml, src/solver/zeroinstall_solver.mli, src/tests/data/driven.xml, src/tests/data/solves.xml, src/tests/test_0install.ml, src/tests/test_solver.ml, src/zeroinstall/solver.ml
If a restriction didn't remove any candidates (either because it matched all of them or because another restriction already removed them) then don't bother reporting it.
Also, don't bother reporting a restriction that only removed candidates worse than the selected one (if any).
For user-provided restrictions, filter the rejects to show only the version(s) the user asked for (unless that would remove all of them). Since we only show the first 5 rejects, this would often mean that the
interesting candidates weren't even shown.
Also, improve the printing of impls. Allow the library user to specify the formatting, and change the default from `sha256=... (1)` to `v1 (sha256=...`) and truncate the hash.
Example output for  `0install select 0compile -c --version-for …
=> Only report restrictions that affected the result

install.sh.src, src/cli/main.ml
- Avoid possible SIGPIPE in `install.sh`.
If we're very unlucky then `./0install --version | head -1` can fail because 0install may do the write in two parts and head may close the pipe between them.
- Handle SIGPIPE using exceptions.
There are some CI cases where the unit-tests failed with `test alias src/tests/runtest (got signal PIPE)`. Make sure that we handle these errors using exceptions, not signals. At least, this should show where they're coming from.
=> Improve SIGPIPE handling

zeroinstall/injector/fetch.py
This is required for Python 3 compatibility.
Fixes #166
=> Explicitly encode string as UTF-8 bytes

src/solver/diagnostics.ml, src/solver/sat.ml, src/solver/sat.mli, src/solver/solver_core.ml, src/tests/data/solves.xml
When an implementation has an optional dependency or a restriction on another interface then we add a clause to ensure that we don't select both it and the conflicting implementation(s), e.g.
at_most_one [impl; conflict_impl]
However, if `impl` conflicts with itself then we get:
at_most_one [impl; impl]
This triggered an assertion failure:
Assert_failure duniverse/0install/src/solver/sat.ml:602:6
Now we report e.g.
- /root/foo.xml -> (problem)
Rejected candidates:
v1 (1): Requires /root/foo.xml version 0
Fixes #179.
=> Handle implementations that directly conflict with themselves

src/gui_gtk/icon_cache.ml, src/support/stream.ml, src/support/stream.mli, src/tests/pk_service.ml, src/zeroinstall/packagekit.ml, src/zeroinstall/version.ml
Avoids compiler warnings on OCaml 4.14 (and failure on OCaml 5.00).
=> Replace uses of deprecated Stdlib.Stream and Lwt_unix.yield

0install.opam, src/support/json.ml, src/zeroinstall/exec.ml, src/zeroinstall/json_connection.ml, src/zeroinstall/json_connection.mli, src/zeroinstall/requirements.mli
Yojson 2.0 removes the `json` type, so this code switches to using `t`.
=> Make compatible with Yojson `json` type deprecation

src/gui_gtk/dune, src/zeroinstall/gui.ml
It seems that dune always builds the plugin as `gui_gtk.cmxs`, even when it's actually bytecode.
Not sure if this will actually let the GUI run, but at least it fixes the build and it will run without the GUI OK.
=> Fix plugin loading on bytecode-only systems

.github/workflows/build.yml, .gitignore, 0install-python.xml, 0install-python.xml.template, 0install.sh, GitVersion.yml, zeroinstall/0launch-gui/gui.py, zeroinstall/__init__.py
- Rename `ZeroInstall.xml` to `0install-python.xml`
- Add CI with GitHub Actions
- Replace `0release` with `0template`
- Automatically publish release on Git tag
When a new Git tag is pushed to the repository, the GitHub pipeline will do the following:
1. Determine the version number from Git tag and `sed` it into the code
2. Run `make translations` and `0test`
3. Run `0template` to generate `0install-python-1.2.3.xml` and `0install-python-1.2.3.tar.gz`
4. Create a GitHub Release with `0install-python-1.2.3.xml` and `0install-python-1.2.3.tar.gz` as artifacts
5. Trigger another GitHub pipeline in the [0install/apps](https://github.com/0install/apps) repo, passing the URLs of  `0install-python-1.2.3.xml` and `0install-python-1.2.3.tar.gz` as inputs
- This pipeline adds …
=> Automate release of Python version
